
graph LR
    
    A["Settlement Areas"] --> B
    D --> E["Grading Settlements"]
    B --> D(["Reclassify"])
    B(["Euclidean Distance"])

    classDef process fill:#00a900
    class B,D,Q,R process;







